let start={{timeStart}};
let end={{timeEnd}};
let events = union isfuzzy=true withsource=tableName pageViews, requests
| where timestamp between (start..end);
let pageViewsCount = toscalar(events | where tableName == "pageViews" | count);
let requestsCount = toscalar(events | where tableName == "requests" | count);
let userAuthCount = toscalar(events | where isnotempty(user_AuthenticatedId) | summarize dcount(user_AuthenticatedId));
let userAnonCount = toscalar(events | where isnotempty(user_Id) | summarize dcount(user_Id));
let sessionCount = toscalar(events | where isnotempty(session_Id) | summarize dcount(session_Id));
let requestSessionCount = toscalar(events | where tableName == "requests" and isnotempty(session_Id) | summarize dcount(session_Id));
let browserCount = toscalar(events | where isnotempty(client_Browser) | count);
let osCount = toscalar(events | where isnotempty(client_OS) | count);
let deviceCount = toscalar(events | where isnotempty(client_Type) | count);
let geoCount = toscalar(events | where isnotempty(client_CountryOrRegion) | count);
let latestTimestamp = toscalar(events | summarize max(timestamp));
let browserTimingsCount = toscalar(union isfuzzy=true browserTimings | where timestamp between (start..end) | count);
print pageViewsCount, requestsCount, userAuthCount, userAnonCount, sessionCount, requestSessionCount,
      browserCount, osCount, deviceCount, geoCount, browserTimingsCount, latestTimestamp
