// Keren Analytics — production infrastructure on Azure Container Apps.
//
// Deploys (resource-group scope):
//   - Log Analytics workspace      (logs sink for the Container Apps env)
//   - Container Apps environment   (the runtime)
//   - Azure Container Registry     (Basic SKU, AcrPull granted to the MI)
//   - User-assigned Managed Identity (image pull from ACR, Foundry, Blob)
//   - Storage Account + private    (off-host SQLite backups; in-process
//     `sqlite-backups` Blob container scheduler writes hourly snapshots)
//   - Container App                (single-replica web ingress on :3000,
//                                    optionally bound to a custom domain)
//
// Secrets (SESSION_SECRET, AZURE_CLIENT_SECRET) live as Container App secrets,
// passed in via @secure() params. They are encrypted at rest by Azure.
// Key Vault rotation/audit can be layered on later as a Phase B; not needed
// for first deploy.
//
// Custom domain: when `customDomainName` is set (e.g. keren.run),
// the template binds it to ingress using an *existing* managed certificate
// referenced by `customDomainCertificateName`. The cert must be provisioned
// out-of-band first (CNAME → asuid.<sub> TXT → managed cert via portal/CLI)
// because the cert provisioning depends on DNS being live, which is not
// expressible in pure IaC. See docs/maintainer-todo.md.
//
// First deploy uses a placeholder image (Microsoft hello-world). After the
// real image is pushed to ACR, run `az containerapp update --image ...` or
// re-deploy this template with `containerImage` overridden.

targetScope = 'resourceGroup'

@description('Azure region for all resources.')
param location string = resourceGroup().location

@description('Short name used as a prefix for all resources. Lowercase, alphanumeric + hyphens, 3-20 chars.')
@minLength(3)
@maxLength(20)
param namePrefix string = 'keren-analytics'

@description('Container image (registry/repository:tag). Use a hello-world placeholder for the first deploy, then update with the real image.')
param containerImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Entra ID app registration client (application) ID. Required for OAuth login.')
param azureClientId string

@description('Entra ID app registration client secret. @secure — never logged.')
@secure()
param azureClientSecret string

@description('Entra ID tenant scope: "organizations" (multi-tenant work accounts), "common", or a specific tenant GUID.')
param azureTenantId string = 'organizations'

@description('Explicit OAuth redirect URI override. Leave empty to auto-compute from customDomainName (preferred) or the Container App FQDN (fallback set post-deploy by the script when no custom domain is configured).')
param azureRedirectUri string = ''

@description('Custom domain bound to ingress (e.g. keren.run). Empty = ingress reachable via the azurecontainerapps.io FQDN only. Requires customDomainCertificateName to be set.')
param customDomainName string = ''

@description('Name of an existing managedCertificate resource on the Container Apps environment. Required when customDomainName is set. The cert must be provisioned out-of-band (CNAME live → portal/CLI creates the managed cert) before this template can bind it.')
param customDomainCertificateName string = ''

@description('Additional custom domains to bind to ingress *alongside* the primary customDomainName — e.g. keep a legacy domain bound during a migration to the new primary. Each item: { name: string, certificateName: string } where certificateName is an existing managedCertificate on the environment. The primary customDomainName alone drives the OAuth redirect URI; these secondary domains do not. Remove an item here to retire that domain on the next deploy.')
param additionalCustomDomains array = []

@description('Express session signing secret. Generated by the deploy script; rotate by re-deploying with a new value (invalidates active sessions). @secure.')
@secure()
param sessionSecret string

@description('Daily ingestion cap (GB) on the Log Analytics workspace — a hard backstop against a runaway self-telemetry bill during a traffic spike. Ingestion stops for the rest of the UTC day once hit (probe/console logs included). -1 disables the cap. Raise for legitimately high traffic.')
@minValue(-1)
param logAnalyticsDailyQuotaGb int = 5

@description('Number of CPU cores per replica.')
param cpuCores string = '0.5'

@description('Memory per replica.')
param memorySize string = '1Gi'

// The app REQUIRES a single replica: sessions are in-memory, the SQLite DB
// is a single file, and restore-on-boot assumes no concurrent writers.
// Defaults are therefore 1/1 — do NOT raise maxReplicas without shipping a
// shared session store + shared/replicated DB first (Phase 3). Scale-to-zero
// (minReplicas=0) is also avoided so cold starts don't drop the warmed cache.
@description('Minimum replicas. Keep at 1 (single-replica invariant — see Phase 3).')
@minValue(0)
@maxValue(10)
param minReplicas int = 1

@description('Maximum replicas. Keep at 1 (single-replica invariant — see Phase 3).')
@minValue(1)
@maxValue(30)
param maxReplicas int = 1

@description('AI provider for the setup-wizard / mapping analysis. "none" disables LLM calls; "azure-foundry" wires the Foundry Responses API. ADR 0005 + Track F3.')
@allowed([
  'none'
  'azure-foundry'
])
param aiProvider string = 'none'

@description('Azure AI Foundry project Responses API endpoint (full URL including /openai/v1/responses). Only used when aiProvider = azure-foundry.')
param azureFoundryEndpoint string = ''

@description('Azure AI Foundry model deployment name (e.g. gpt-5.4-mini). Only used when aiProvider = azure-foundry.')
param azureFoundryDeployment string = ''

@description('Enable the in-process SQLite → Azure Blob backup scheduler. Defaults to true in prod; set to false to skip uploads (the Storage Account is still provisioned).')
param backupEnabled bool = true

@description('Hours between backup snapshots. Default 1h.')
@minValue(1)
@maxValue(24)
param backupIntervalHours int = 1

@description('Maximum snapshots retained in the Blob container. Older ones are pruned.')
@minValue(1)
@maxValue(168)
param backupMaxSnapshots int = 24

@description('Enable self-telemetry: the app emits its own telemetry to the provisioned Application Insights so a Keren dashboard can be pointed at Keren itself (dogfooding). Server SDK feeds the Technical view; the browser SDK feeds the Marketing/Readiness views.')
param telemetryEnabled bool = true

// --- Globally-unique names (ACR + Storage Account must be unique across all of Azure) ---
var uniqueSuffix = uniqueString(resourceGroup().id)
var acrName = toLower(replace('${namePrefix}${uniqueSuffix}', '-', ''))
// Storage Account name: 3-24 chars, lowercase alphanumeric only.
var storageAccountName = toLower(take(replace('stkbk${namePrefix}${uniqueSuffix}', '-', ''), 24))
var backupContainerName = 'sqlite-backups'
var logAnalyticsName = 'la-${namePrefix}'
var appInsightsName = 'appi-${namePrefix}'
var containerEnvName = 'cae-${namePrefix}'
var containerAppName = 'ca-${namePrefix}'
var managedIdentityName = 'id-${namePrefix}'

// --- Computed redirect URI ---
// Priority: explicit override > custom domain > empty (deploy script patches
// post-deploy with the Azure FQDN when neither is set).
var effectiveRedirectUri = !empty(azureRedirectUri)
  ? azureRedirectUri
  : (!empty(customDomainName) ? 'https://${customDomainName}/auth/callback' : '')

// --- Computed customDomains block (conditional) ---
// Primary domain (customDomainName) + any additionalCustomDomains are bound
// together. The primary alone feeds effectiveRedirectUri above.
var primaryCustomDomainBinding = (!empty(customDomainName) && !empty(customDomainCertificateName))
  ? [
      {
        name: customDomainName
        certificateId: '${containerEnv.id}/managedCertificates/${customDomainCertificateName}'
        bindingType: 'SniEnabled'
      }
    ]
  : []

var additionalCustomDomainBindings = [
  for d in additionalCustomDomains: {
    name: d.name
    certificateId: '${containerEnv.id}/managedCertificates/${d.certificateName}'
    bindingType: 'SniEnabled'
  }
]

var customDomainBindings = concat(primaryCustomDomainBinding, additionalCustomDomainBindings)

// --- Log Analytics (required by Container Apps env) ---

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsName
  location: location
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 30
    workspaceCapping: {
      dailyQuotaGb: logAnalyticsDailyQuotaGb
    }
  }
}

// --- Application Insights (self-telemetry — Keren observing itself) ---
// Workspace-based, reusing the Log Analytics above (no second workspace).
// DisableLocalAuth stays FALSE on purpose: the browser SDK authenticates
// with the connection string's ingestion key (write-only — it can post
// telemetry, never read it), which Entra-only ingestion would forbid. The
// server SDK uses the same connection string. See docs/maintainer-todo.md.
resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalytics.id
    DisableLocalAuth: false
    IngestionMode: 'LogAnalytics'
  }
}

// --- User-assigned Managed Identity (used to pull from ACR, call Foundry, write Blobs) ---

resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityName
  location: location
}

// --- Azure Container Registry ---

resource acr 'Microsoft.ContainerRegistry/registries@2023-11-01-preview' = {
  name: acrName
  location: location
  sku: { name: 'Basic' }
  properties: {
    adminUserEnabled: false
  }
}

// AcrPull role on the ACR for the Managed Identity
resource acrPullRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: acr
  name: guid(acr.id, managedIdentity.id, 'AcrPull')
  properties: {
    // 7f951dda-4ed3-4680-a7ca-43fe172d538d = AcrPull built-in role
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d')
    principalId: managedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// --- Storage Account for off-host SQLite snapshots ---

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: storageAccountName
  location: location
  sku: { name: 'Standard_LRS' }
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2023-05-01' = {
  parent: storageAccount
  name: 'default'
  properties: {}
}

resource backupsContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  parent: blobService
  name: backupContainerName
  properties: {
    publicAccess: 'None'
  }
}

// Storage Blob Data Contributor on the Storage Account for the MI. Scoped
// to the account rather than the container so the in-process scheduler can
// also create new containers if we ever need a second prefix.
resource blobContributorRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: storageAccount
  name: guid(storageAccount.id, managedIdentity.id, 'StorageBlobDataContributor')
  properties: {
    // ba92f5b4-2d11-453d-a403-e96b0029c9fe = Storage Blob Data Contributor
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
    principalId: managedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// --- Container Apps environment ---

resource containerEnv 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: containerEnvName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
  }
}

// --- Container App ---

resource containerApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: containerAppName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    managedEnvironmentId: containerEnv.id
    configuration: {
      ingress: {
        external: true
        targetPort: 3000
        transport: 'auto'
        allowInsecure: false
        customDomains: customDomainBindings
      }
      registries: [
        {
          server: acr.properties.loginServer
          identity: managedIdentity.id
        }
      ]
      secrets: [
        { name: 'session-secret', value: sessionSecret }
        { name: 'azure-client-secret', value: azureClientSecret }
      ]
    }
    template: {
      containers: [
        {
          name: 'app'
          image: containerImage
          resources: {
            cpu: json(cpuCores)
            memory: memorySize
          }
          env: [
            { name: 'NODE_ENV', value: 'production' }
            { name: 'AZURE_MODE', value: 'real' }
            { name: 'AZURE_CLIENT_ID', value: azureClientId }
            { name: 'AZURE_TENANT_ID', value: azureTenantId }
            { name: 'AZURE_REDIRECT_URI', value: effectiveRedirectUri }
            { name: 'SESSION_SECRET', secretRef: 'session-secret' }
            { name: 'AZURE_CLIENT_SECRET', secretRef: 'azure-client-secret' }
            // Track F3 — AI mapping analysis. AZURE_FOUNDRY_CLIENT_ID points
            // the @azure/identity SDK at the user-assigned MI for backend
            // calls (separate from AZURE_CLIENT_ID, which is reserved for the
            // OAuth user app registration). The MI must hold the
            // `Azure AI User` role on the Foundry account/project — see
            // docs/maintainer-todo.md.
            { name: 'AI_PROVIDER', value: aiProvider }
            { name: 'AZURE_FOUNDRY_ENDPOINT', value: azureFoundryEndpoint }
            { name: 'AZURE_FOUNDRY_DEPLOYMENT', value: azureFoundryDeployment }
            { name: 'AZURE_FOUNDRY_CLIENT_ID', value: managedIdentity.properties.clientId }
            // In-process SQLite → Blob backup. Empty BACKUP_BLOB_ACCOUNT
            // disables the scheduler (no-op); the same MI used by Foundry
            // also holds Storage Blob Data Contributor on this account.
            { name: 'BACKUP_BLOB_ACCOUNT', value: backupEnabled ? storageAccount.name : '' }
            { name: 'BACKUP_BLOB_CONTAINER', value: backupContainerName }
            { name: 'BACKUP_INTERVAL_MS', value: string(backupIntervalHours * 3600000) }
            { name: 'BACKUP_MAX_SNAPSHOTS', value: string(backupMaxSnapshots) }
            // Self-telemetry. The same connection string drives the server
            // SDK and the page-served browser bootstrap (/telemetry.js); the
            // ingestion key it carries is write-only by design.
            { name: 'TELEMETRY_ENABLED', value: telemetryEnabled ? 'true' : 'false' }
            { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: telemetryEnabled ? appInsights.properties.ConnectionString : '' }
            { name: 'TELEMETRY_SERVICE_NAME', value: containerAppName }
          ]
          probes: [
            {
              type: 'Liveness'
              httpGet: { path: '/healthz', port: 3000 }
              initialDelaySeconds: 10
              periodSeconds: 30
            }
            {
              type: 'Readiness'
              httpGet: { path: '/healthz', port: 3000 }
              initialDelaySeconds: 5
              periodSeconds: 10
            }
          ]
        }
      ]
      scale: {
        minReplicas: minReplicas
        maxReplicas: maxReplicas
      }
    }
  }
  dependsOn: [
    acrPullRoleAssignment
    blobContributorRoleAssignment
  ]
}

// --- Outputs (used by the wrapper script) ---

output acrLoginServer string = acr.properties.loginServer
output acrName string = acr.name
output managedIdentityClientId string = managedIdentity.properties.clientId
output managedIdentityPrincipalId string = managedIdentity.properties.principalId
output containerAppName string = containerApp.name
output containerAppFqdn string = containerApp.properties.configuration.ingress.fqdn
output containerEnvName string = containerEnv.name
output storageAccountName string = storageAccount.name
output appInsightsName string = appInsights.name
output backupContainerName string = backupContainerName
output effectiveRedirectUri string = effectiveRedirectUri
output customDomainConfigured bool = !empty(customDomainName) && !empty(customDomainCertificateName)
