// Keren Analytics — production infrastructure on Azure Container Apps.
//
// Deploys (resource-group scope):
//   - Log Analytics workspace      (logs sink for the Container Apps env)
//   - Container Apps environment   (the runtime)
//   - Azure Container Registry     (Basic SKU, AcrPull granted to the MI)
//   - User-assigned Managed Identity (image pull from ACR)
//   - Container App                (single-replica web ingress on :3000)
//
// Secrets (SESSION_SECRET, AZURE_CLIENT_SECRET) live as Container App secrets,
// passed in via @secure() params. They are encrypted at rest by Azure.
// Key Vault rotation/audit can be layered on later as a Phase B; not needed
// for first deploy.
//
// First deploy uses a placeholder image (Microsoft hello-world). After the
// real image is pushed to ACR, run `az containerapp update --image ...` or
// re-deploy this template with `containerImage` overridden.

targetScope = 'resourceGroup'

@description('Azure region for all resources.')
param location string = resourceGroup().location

@description('Short name used as a prefix for all resources. Lowercase, alphanumeric + hyphens, 3-20 chars.')
@minLength(3)
@maxLength(20)
param namePrefix string = 'keren-analytics'

@description('Container image (registry/repository:tag). Use a hello-world placeholder for the first deploy, then update with the real image.')
param containerImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Entra ID app registration client (application) ID. Required for OAuth login.')
param azureClientId string

@description('Entra ID app registration client secret. @secure — never logged.')
@secure()
param azureClientSecret string

@description('Entra ID tenant scope: "organizations" (multi-tenant work accounts), "common", or a specific tenant GUID.')
param azureTenantId string = 'organizations'

@description('OAuth redirect URI. Leave empty for first deploy — re-run after Container App FQDN is known. Final value should be https://analytics.keren.run/auth/callback once DNS is configured.')
param azureRedirectUri string = ''

@description('Express session signing secret. Generated by the deploy script; rotate by re-deploying with a new value (invalidates active sessions). @secure.')
@secure()
param sessionSecret string

@description('Number of CPU cores per replica.')
param cpuCores string = '0.5'

@description('Memory per replica.')
param memorySize string = '1Gi'

@description('Minimum replicas. Set to 0 for scale-to-zero (cheaper, slower cold start).')
@minValue(0)
@maxValue(10)
param minReplicas int = 0

@description('Maximum replicas.')
@minValue(1)
@maxValue(30)
param maxReplicas int = 3

@description('AI provider for the setup-wizard / mapping analysis. "none" disables LLM calls; "azure-foundry" wires the Foundry Responses API. ADR 0005 + Track F3.')
@allowed([
  'none'
  'azure-foundry'
])
param aiProvider string = 'none'

@description('Azure AI Foundry project Responses API endpoint (full URL including /openai/v1/responses). Only used when aiProvider = azure-foundry.')
param azureFoundryEndpoint string = ''

@description('Azure AI Foundry model deployment name (e.g. gpt-5.4-mini). Only used when aiProvider = azure-foundry.')
param azureFoundryDeployment string = ''

// --- Globally-unique names (ACR must be unique across all of Azure) ---
var uniqueSuffix = uniqueString(resourceGroup().id)
var acrName = toLower(replace('${namePrefix}${uniqueSuffix}', '-', ''))
var logAnalyticsName = 'la-${namePrefix}'
var containerEnvName = 'cae-${namePrefix}'
var containerAppName = 'ca-${namePrefix}'
var managedIdentityName = 'id-${namePrefix}'

// --- Log Analytics (required by Container Apps env) ---

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsName
  location: location
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 30
  }
}

// --- User-assigned Managed Identity (used to pull from ACR) ---

resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityName
  location: location
}

// --- Azure Container Registry ---

resource acr 'Microsoft.ContainerRegistry/registries@2023-11-01-preview' = {
  name: acrName
  location: location
  sku: { name: 'Basic' }
  properties: {
    adminUserEnabled: false
  }
}

// AcrPull role on the ACR for the Managed Identity
resource acrPullRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: acr
  name: guid(acr.id, managedIdentity.id, 'AcrPull')
  properties: {
    // 7f951dda-4ed3-4680-a7ca-43fe172d538d = AcrPull built-in role
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d')
    principalId: managedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// --- Container Apps environment ---

resource containerEnv 'Microsoft.App/managedEnvironments@2024-03-01' = {
  name: containerEnvName
  location: location
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
  }
}

// --- Container App ---

resource containerApp 'Microsoft.App/containerApps@2024-03-01' = {
  name: containerAppName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    managedEnvironmentId: containerEnv.id
    configuration: {
      ingress: {
        external: true
        targetPort: 3000
        transport: 'auto'
        allowInsecure: false
      }
      registries: [
        {
          server: acr.properties.loginServer
          identity: managedIdentity.id
        }
      ]
      secrets: [
        { name: 'session-secret', value: sessionSecret }
        { name: 'azure-client-secret', value: azureClientSecret }
      ]
    }
    template: {
      containers: [
        {
          name: 'app'
          image: containerImage
          resources: {
            cpu: json(cpuCores)
            memory: memorySize
          }
          env: [
            { name: 'NODE_ENV', value: 'production' }
            { name: 'AZURE_MODE', value: 'real' }
            { name: 'AZURE_CLIENT_ID', value: azureClientId }
            { name: 'AZURE_TENANT_ID', value: azureTenantId }
            { name: 'AZURE_REDIRECT_URI', value: azureRedirectUri }
            { name: 'SESSION_SECRET', secretRef: 'session-secret' }
            { name: 'AZURE_CLIENT_SECRET', secretRef: 'azure-client-secret' }
            // Track F3 — AI mapping analysis. AZURE_FOUNDRY_CLIENT_ID points
            // the @azure/identity SDK at the user-assigned MI for backend
            // calls (separate from AZURE_CLIENT_ID, which is reserved for the
            // OAuth user app registration). The MI must hold the
            // `Azure AI User` role on the Foundry Project — see
            // docs/maintainer-todo.md.
            { name: 'AI_PROVIDER', value: aiProvider }
            { name: 'AZURE_FOUNDRY_ENDPOINT', value: azureFoundryEndpoint }
            { name: 'AZURE_FOUNDRY_DEPLOYMENT', value: azureFoundryDeployment }
            { name: 'AZURE_FOUNDRY_CLIENT_ID', value: managedIdentity.properties.clientId }
          ]
          probes: [
            {
              type: 'Liveness'
              httpGet: { path: '/auth/session', port: 3000 }
              initialDelaySeconds: 10
              periodSeconds: 30
            }
            {
              type: 'Readiness'
              httpGet: { path: '/auth/session', port: 3000 }
              initialDelaySeconds: 5
              periodSeconds: 10
            }
          ]
        }
      ]
      scale: {
        minReplicas: minReplicas
        maxReplicas: maxReplicas
      }
    }
  }
  dependsOn: [
    acrPullRoleAssignment
  ]
}

// --- Outputs (used by the wrapper script) ---

output acrLoginServer string = acr.properties.loginServer
output acrName string = acr.name
output managedIdentityClientId string = managedIdentity.properties.clientId
output managedIdentityPrincipalId string = managedIdentity.properties.principalId
output containerAppName string = containerApp.name
output containerAppFqdn string = containerApp.properties.configuration.ingress.fqdn
output containerEnvName string = containerEnv.name
