/**
 * Public telemetry contract (ADR 0006, Phase 0).
 *
 * The "what to emit so Keren lights up green from day one" spec, served to
 * coding agents (Cursor / Copilot / Claude Code) at a stable URL so they can
 * instrument an app's Application Insights telemetry *before* it ever reaches
 * the setup wizard.
 *
 * Single source of truth: every value here is DERIVED from the modules that
 * already drive the product — the readiness scorer (`readinessScore.js`), the
 * canonical mapping (`mapping.js`), and the in-app remediation prompts
 * (`promptGenerator.js`). Nothing about "what Keren wants" is re-stated by
 * hand, so the published contract can never drift from runtime behaviour.
 * `tests/telemetryContract.test.js` pins that invariant; the committed
 * snapshots under `public/` are regenerated by `npm run build:contract`.
 */

import crypto from "node:crypto";
import {
  SIGNAL_WEIGHTS,
  GRADE_THRESHOLDS,
} from "./readinessScore.js";
import { ALIASES, mappingExpressions } from "./mapping.js";
import {
  STACK_HINTS,
  PROMPT_TEMPLATES,
  signalLabel,
} from "./promptGenerator.js";

const PRODUCT = {
  name: "Keren Analytics",
  url: "https://keren.run",
  repository: "https://github.com/lionelgarnier/keren-analytics",
  description:
    "Plug-and-play analytics over Azure Application Insights telemetry. " +
    "This contract tells coding agents which signals to emit, how to name " +
    "custom dimensions, and which config values make telemetry render well.",
};

// Where each readiness signal lands in Application Insights and how it is
// produced. This is the contract's own knowledge (App Insights specifics that
// don't live in any scorer/mapping module); the weight/category/label/
// description for each signal are pulled from SIGNAL_WEIGHTS below so they
// stay in lockstep with the score. `userIdDegraded` is intentionally omitted:
// it is the sparse-data variant of `userId`, not a separate thing to emit.
const SIGNAL_DETAIL = {
  pageViews: {
    appInsightsTable: "pageViews",
    howToEmit:
      "Application Insights JS SDK: enable enableAutoRouteTracking for SPAs, " +
      "or call trackPageView() on each route/page load.",
    verifyKql: "pageViews | summarize count() by bin(timestamp, 1h)",
  },
  requests: {
    appInsightsTable: "requests",
    howToEmit:
      "Server SDK request auto-collection (applicationinsights for Node, " +
      "Microsoft.ApplicationInsights for .NET, the Java agent, " +
      "opencensus-ext-azure for Python).",
    verifyKql: "requests | summarize count() by bin(timestamp, 1h)",
  },
  sessionId: {
    appInsightsField: "session_Id",
    howToEmit:
      "Auto-generated by the JS SDK — do not set disableSessionTracking. " +
      "Server-only telemetry has no sessions; add a frontend SDK.",
    verifyKql: "pageViews | where isnotempty(session_Id) | count",
  },
  userId: {
    appInsightsField: "user_AuthenticatedId",
    howToEmit:
      "Call setAuthenticatedUserContext(hashedId) right after login on both " +
      "frontend and backend. Use a stable pseudonymous id — never raw email.",
    verifyKql:
      "pageViews | where isnotempty(user_AuthenticatedId) | summarize dcount(user_AuthenticatedId) by bin(timestamp, 1d)",
  },
  userAgent: {
    appInsightsFields: ["client_Browser", "client_OS", "client_Type"],
    howToEmit: "Auto-collected by the JS SDK from the User-Agent header.",
    verifyKql: "pageViews | where isnotempty(client_Browser) | count",
  },
  geo: {
    appInsightsField: "client_CountryOrRegion",
    howToEmit:
      "Server-side IP geo-enrichment by Azure. Behind a proxy/CDN, forward " +
      "X-Forwarded-For so the client IP (not the proxy's) is resolved.",
    verifyKql:
      "pageViews | where isnotempty(client_CountryOrRegion) | summarize count() by client_CountryOrRegion",
  },
  browserTimings: {
    appInsightsTable: "browserTimings",
    howToEmit:
      "JS SDK with enableAutoRouteTracking + autoTrackPageVisitTime; keep " +
      "sampling moderate so timings aren't filtered out.",
    verifyKql: "browserTimings | summarize count() by bin(timestamp, 1h)",
  },
  dependencies: {
    appInsightsTable: "dependencies",
    howToEmit: "Enable dependency auto-collection in the server SDK config.",
    verifyKql: "dependencies | summarize count() by type",
  },
  exceptions: {
    appInsightsTable: "exceptions",
    howToEmit:
      "Server SDK exception auto-collection plus trackException() in a global " +
      "error handler.",
    verifyKql: "exceptions | summarize count() by bin(timestamp, 1h)",
  },
};

// Best-practice config values, distilled from Keren's own dogfooding
// instrumentation (src/telemetry.js) and the App Insights SDK guidance baked
// into the remediation prompts. These are advice for the agent, not runtime
// values, so they live here rather than in a scorer module.
const INSTRUMENTATION_CONFIG = [
  {
    id: "connection-string",
    title: "Connection string from env, never hardcoded",
    detail:
      "Read the App Insights connection string from APPLICATIONINSIGHTS_CONNECTION_STRING. " +
      "Never commit it. The browser SDK uses a write-only ingestion key — safe to expose to the page.",
  },
  {
    id: "init-order",
    title: "Initialize the SDK first",
    detail:
      "Set up the server SDK before the web framework loads (first import) so the HTTP stack is patched and requests/dependencies are auto-collected.",
  },
  {
    id: "no-pii",
    title: "No PII in telemetry",
    detail:
      "Never emit email, full name, raw IP, or tokens. Pseudonymize user ids (hash). Keren scrubs known PII patterns from samples, but the contract is: don't send it.",
  },
  {
    id: "exclude-health-checks",
    title: "Exclude health-check endpoints",
    detail:
      "Filter probe routes (e.g. /healthz) out of request telemetry so they don't drown real traffic in the Technical view.",
  },
  {
    id: "flush-on-shutdown",
    title: "Flush on shutdown",
    detail:
      "Flush pending telemetry on SIGTERM so the last batch of events isn't lost when the container stops.",
  },
  {
    id: "cloud-role",
    title: "Set cloud_RoleName per service",
    detail:
      "Tag each service with a distinct cloud_RoleName so multi-service topologies stay distinguishable in the dashboard.",
  },
  {
    id: "sampling",
    title: "Sample, but not away your conversions",
    detail:
      "Use adaptive sampling to control cost, but keep it moderate enough that low-volume conversion events and browser timings survive.",
  },
];

// Canonical fields whose custom-dimension naming Keren auto-detects. Derived
// straight from the alias table + mapping expressions: an agent that names a
// custom dimension one of `recognizedNames` skips manual mapping in the wizard.
function buildNamingConventions() {
  return Object.keys(ALIASES).map((field) => {
    const exprs = mappingExpressions[field] || {};
    const builtinExpressions = Object.entries(exprs)
      .filter(([variant]) => variant !== "custom")
      .map(([, expr]) => expr);
    const customDimensionExpression = exprs.custom || null;
    return {
      canonicalField: field,
      builtinExpressions,
      customDimensionExpression,
      recommendedCustomDimensionName: ALIASES[field].exact[0],
      recognizedNames: ALIASES[field].exact.slice(),
      recognizedNamePattern: ALIASES[field].pattern.source,
      note:
        "If you emit this as a custom dimension, name it one of recognizedNames " +
        "(or match recognizedNamePattern) so Keren auto-maps it with no manual setup.",
    };
  });
}

function buildSignals() {
  return Object.entries(SIGNAL_WEIGHTS)
    .filter(([key]) => key !== "userIdDegraded")
    .map(([key, weight]) => ({
      id: key,
      label: weight.label,
      points: weight.points,
      category: weight.category,
      description: weight.description,
      ...(SIGNAL_DETAIL[key] || {}),
    }))
    .sort((a, b) => b.points - a.points);
}

function buildRecipes() {
  const stack = STACK_HINTS.generic;
  // Iterate the SCORED signals (minus the userIdDegraded variant), not
  // PROMPT_TEMPLATES' own keys — otherwise the recipe set silently drifts from
  // the signal set: dependencies/exceptions (10 pts each) had no recipe while
  // userIdDegraded (not a signal) had one. Every scored signal must have a
  // template; the anti-drift test enforces it.
  return Object.keys(SIGNAL_WEIGHTS)
    .filter((signal) => signal !== "userIdDegraded")
    .map((signal) => {
      const template = PROMPT_TEMPLATES[signal];
      if (!template) {
        throw new Error(`No PROMPT_TEMPLATES entry for scored signal "${signal}"`);
      }
      return { signal, label: signalLabel(signal), prompt: template(stack, null) };
    });
}

/**
 * Build the public telemetry contract. Deterministic except for
 * `generatedAt`: `contractVersion` is a content hash that excludes the
 * timestamp, so it only changes when the underlying signals/mapping/prompts
 * change — agents can cache against it.
 *
 * @returns {object} the contract
 */
export function buildTelemetryContract() {
  const maxScore = Object.entries(SIGNAL_WEIGHTS).reduce(
    (sum, [key, w]) => (key === "userIdDegraded" ? sum : sum + w.points),
    0
  );

  const body = {
    product: PRODUCT,
    privacy: {
      rawLogsLeaveTenant: false,
      summary:
        "Keren stores only aggregates — no raw log rows, no PII. Telemetry you " +
        "emit is queried in place via KQL; pseudonymize user ids and never send PII.",
    },
    scoring: {
      maxScore,
      grades: GRADE_THRESHOLDS,
      note:
        "Score = sum of points for signals present. Aim for grade A (>=90%). " +
        "Points and grades mirror the live readiness scorer.",
    },
    signals: buildSignals(),
    namingConventions: buildNamingConventions(),
    instrumentationConfig: INSTRUMENTATION_CONFIG,
    stacks: Object.entries(STACK_HINTS).map(([key, hint]) => ({
      key,
      name: hint.name,
      recommendedSdk: hint.sdk,
    })),
    recipes: buildRecipes(),
  };

  const contractVersion = crypto
    .createHash("sha256")
    .update(JSON.stringify(body))
    .digest("hex")
    .slice(0, 12);

  return {
    $schema: `${PRODUCT.url}/.well-known/telemetry-contract.json`,
    contractVersion,
    generatedAt: new Date().toISOString(),
    ...body,
  };
}

/**
 * Render the contract as an llms.txt-style Markdown brief — the human/LLM
 * readable companion to the JSON, discoverable at /llms.txt.
 *
 * @param {object} [contract] - defaults to a freshly built contract
 * @returns {string} Markdown
 */
export function renderContractMarkdown(contract = buildTelemetryContract()) {
  const lines = [];
  lines.push(`# ${contract.product.name} — Telemetry Contract`);
  lines.push("");
  lines.push(`> ${contract.product.description}`);
  lines.push("");
  lines.push(
    `Contract version: \`${contract.contractVersion}\` · ` +
      `Machine-readable: ${contract.product.url}/.well-known/telemetry-contract.json`
  );
  lines.push("");
  lines.push(
    "Instrument your app's Azure Application Insights so these signals are " +
      "present, name custom dimensions as below, and Keren renders the full " +
      "dashboard with no manual mapping.");
  lines.push("");

  lines.push("## Privacy");
  lines.push("");
  lines.push(`- ${contract.privacy.summary}`);
  lines.push("");

  lines.push("## Signals (readiness points)");
  lines.push("");
  lines.push(`Score out of ${contract.scoring.maxScore}. Aim for grade A (>=90%).`);
  lines.push("");
  for (const s of contract.signals) {
    const target =
      s.appInsightsTable
        ? `\`${s.appInsightsTable}\` table`
        : s.appInsightsField
          ? `\`${s.appInsightsField}\``
          : s.appInsightsFields
            ? s.appInsightsFields.map((f) => `\`${f}\``).join(", ")
            : "";
    lines.push(`### ${s.label} — ${s.points} pts (${s.category})`);
    lines.push("");
    lines.push(`- Lands in: ${target}`);
    lines.push(`- How: ${s.howToEmit}`);
    if (s.verifyKql) lines.push(`- Verify (KQL): \`${s.verifyKql}\``);
    lines.push("");
  }

  lines.push("## Custom dimension naming");
  lines.push("");
  lines.push(
    "Built-in fields are detected automatically. If you must use a custom " +
      "dimension, use a recognized name so it auto-maps:");
  lines.push("");
  for (const n of contract.namingConventions) {
    lines.push(
      `- **${n.canonicalField}** → recommended \`${n.recommendedCustomDimensionName}\` ` +
        `(also: ${n.recognizedNames.slice(0, 6).join(", ")}…)`
    );
  }
  lines.push("");

  lines.push("## Config best practices");
  lines.push("");
  for (const c of contract.instrumentationConfig) {
    lines.push(`- **${c.title}** — ${c.detail}`);
  }
  lines.push("");

  lines.push("## SDK per stack");
  lines.push("");
  for (const st of contract.stacks) {
    lines.push(`- ${st.name}: \`${st.recommendedSdk}\``);
  }
  lines.push("");

  lines.push("## Ready-to-paste prompts");
  lines.push("");
  lines.push(
    "One prompt per signal — paste into Cursor / Copilot / Claude Code to " +
      "close a gap. Full text in the JSON contract under `recipes`.");
  lines.push("");
  for (const r of contract.recipes) {
    lines.push(`- ${r.label} (\`${r.signal}\`)`);
  }
  lines.push("");

  return lines.join("\n");
}
